# Overcommit configuration for groove.rb
# Pre-commit hooks for code quality and testing

PreCommit:
  RuboCop:
    enabled: true
    description: 'Run RuboCop on staged files'
    command: ['bundle', 'exec', 'rubocop']
    include: '**/*.rb'
    exclude: 'vendor/**/*'
    quiet: true

  RSpec:
    enabled: false
    description: 'Run RSpec test suite'
    command: ['bundle', 'exec', 'rake', 'spec']
    files: 'spec/**/*_spec.rb'

  Brakeman:
    enabled: true
    description: 'Run Brakeman security scan'
    command: ['bundle', 'exec', 'brakeman', '--force', '--quiet']
