inherit_from: .rubocop_todo.yml

# .rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
  SuggestExtensions: false
  DisabledByDefault: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

require:
  - rubocop-rspec

Capybara/RSpec/PredicateMatcher:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3
